### ISSUE TITLE
Relation between this package and rock-slam/slam-envire

### ISSUE THREAD

**Issue by naveedhd** [envire/slam-maps#19]
Hi,

I am going through this package and [rock-slam/slam-envire](https://github.com/rock-slam/slam-envire) and find a lot of commonalities conceptually but difference in implementation. Can you please explain the main objectives/applications of this package and, if possible, difference with the rock-slam/slam-envire.

Thanks

**Comment by chhtz** [comment]
This package was developed as part of the EnviRe2 development and is supposed to replace [the corresponding subfolder of slam-envire](https://github.com/rock-slam/slam-envire/tree/master/src/maps). In contrast to the old EnviRe, this package can be used without depending on the whole EnviRe package.

If you need to represent a map in Rock for newly created packages, I'd recommend this library. Many legacy algorithms still use the maps from the old Envire, however.

**Comment by naveedhd** [comment]
Thanks for the info!
